export { default as Home } from './Home'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as Gallery } from './Gallery'
export { default as Team } from './Team'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'
